{
 "title": "Cohort platform-core-services Alerts",
 "tags": [
  "PE-Team",
  "Kubernetes"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "EC2 Inbound network traffic per instance (bytes/sec, period 300)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "metricName": "NetworkIn",
     "metricQueryType": 1,
     "namespace": "AWS/EC2",
     "period": "300",
     "queryMode": "Metrics",
     "region": "us-east-2",
     "sql": {
      "from": { "property": { "name": "AWS/EC2", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "property": { "name": "InstanceId", "type": "string" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "NetworkIn", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(NetworkIn) FROM \"AWS/EC2\" GROUP BY InstanceId",
     "statistic": "SampleCount"
    }
   ]
  },
  {
   "title": "EC2 CPU Utilization per instance (Average%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "metricName": "CPUUtilization",
     "metricQueryType": 1,
     "namespace": "AWS/EC2",
     "queryMode": "Metrics",
     "region": "us-east-2",
     "sql": {
      "from": { "property": { "name": "AWS/EC2", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "property": { "name": "InstanceId", "type": "string" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "CPUUtilization", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT AVG(CPUUtilization) FROM \"AWS/EC2\" GROUP BY InstanceId",
     "statistic": "Minimum"
    }
   ]
  },
  { "title": "Core-Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "core-services pod restarts",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{app_kubernetes_io_name=\"kube-state-metrics\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_pod_container_status_restarts_total{container=\"metrics-server\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_pod_container_status_restarts_total{container=\"grafana-agent-logs\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_pod_container_status_restarts_total{container=\"grafana-agent-traces\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_pod_container_status_restarts_total{container=\"prometheus-server\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Monitoring Agents", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Prometheus Monitor Instances Running",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{container=\"prometheus\"})",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Grafana Log Agent Instances Running",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{container=\"grafana-agent-logs\"})",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Grafana Traces Agent Instances Running",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{container=\"grafana-agent-traces\"})",
     "legendFormat": "__auto"
    },
    {}
   ]
  }
 ]
}